/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

// ADC
//UL is unsigned long
#define ADC_BASE_ADDRESS        0x40012000UL
#define ADC_CR1_REG_OFFSET      0x04UL

#define ADC_CR1_ACCESS          (ADC_BASE_ADDRESS + ADC_CR1_REG_OFFSET)

// RCC
#define RCC_BASE_ADDRESS        0x40023800UL
#define RCC_ENABLE_APB2_OFFSET	0x44UL

#define RCC_APB2_ENABLE			(RCC_BASE_ADDRESS + RCC_ENABLE_APB2_OFFSET)

int main(void)
{
	// 1) ENABLE Peripheral Clock
	// ADC is connected to APB2 bus, so enable RCC Peripheral Clk enable registor for APB2
	uint32_t *p_RCCEnableAPB2 = (uint32_t*) RCC_APB2_ENABLE;

	// Set the 8th bit to enable the ADC clk
	 *p_RCCEnableAPB2 = *p_RCCEnableAPB2 | 0x00000100UL;

	//*p_RCCEnableAPB2 = *p_RCCEnableAPB2 | (1 << 8);


	//2) Modify ADC CR1 Reg
	// type cast it to 32bit int because macro
	uint32_t *p_AdcCrt1Reg = (uint32_t*) ADC_CR1_ACCESS;

	// change the 8bit to 1
	*p_AdcCrt1Reg = *p_AdcCrt1Reg | 0x00000100UL;

    /* Loop forever */
	for(;;);
}
