/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDRESS				0x40023800UL
#define RCC_CLK_CONFIG_REG_OFFSET		0x08UL
#define RCC_CLK_CONTROL_REG_OFFSET		0x00UL
#define RCC_ENABLE_AHB1_OFFSET			0x30UL

#define GPIOA_BASE_ADDR					0x40020000UL
#define GPIOA_MODER_OFFSET  			0x0

#define RCC_CLK_CONFIG_REG_ADDR			(RCC_BASE_ADDRESS + RCC_CLK_CONFIG_REG_OFFSET)
#define RCC_CLK_ENABLE_AHB1_ADDR		(RCC_BASE_ADDRESS + RCC_ENABLE_AHB1_OFFSET)
#define RCC_CLK_CTRL_REG_ADDR			(RCC_BASE_ADDRESS + RCC_CLK_CONTROL_REG_OFFSET)

#define GPIOA_MODER_ADDR				(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)


int main(void)
{
	// Step1: Enable the HSEBYP bit of RCC_CR to bypass from crystal oscillator with external clk
	uint32_t *p_RccCTRLReg = (uint32_t*) RCC_CLK_CTRL_REG_ADDR;
	*p_RccCTRLReg = *p_RccCTRLReg | 0x00040000UL;

	// Step2: Enable the HSEON bit to use HSE external clk bit 16
	*p_RccCTRLReg = *p_RccCTRLReg | 0x00010000UL;

	// Step3: Switch systemclock to HSE from RCC_CFGR
	uint32_t *p_RccCFGReg = (uint32_t*) RCC_CLK_CONFIG_REG_ADDR;

	// set bit 0 to 1
	*p_RccCFGReg = *p_RccCFGReg | 0x00000001UL;
	// set bit 1 to 0 - not necessary to do since reset value of this reg is 0x00000000
	*p_RccCFGReg = *p_RccCFGReg & 0xFFFFFFFDUL;

	// Step 4: Do the MC01 settings to measure

	// i) set the bit 22:21 to 01 to configure RCC_CFGR MC01 bit fields to select HSE CLK
	// just set bit 21 to 1
	*p_RccCFGReg = *p_RccCFGReg | 0x00200000UL;

	// ii)) Output to pin PA8 - GPIOA
	// Configure PA8 to AF0 (Alternate function mapping 0) mode t behave as MC01 signal

	// a) since its GPIOA enable the clock peripheral using the RCC clock enable register of AHB1 bus
	uint32_t *pRccEnableAhb1 =  (uint32_t *)RCC_CLK_ENABLE_AHB1_ADDR;

	// set the bits for enable GPIOA clock in AHB1 (bit0)
	*pRccEnableAhb1 = *pRccEnableAhb1 | 0x00000001;

	//b) & c) come back and do after GPIO section

	//b) Configure the mode of GPIOA pin8 as alternate function mapping mode
	uint32_t *p_GPIOAModerReg = (uint32_t*) GPIOA_MODER_ADDR;
	// which moder?




    /* Loop forever */
	for(;;);
}


void FLASH_IRQHandler(void)
{

}
