/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#define RCC_BASE_ADDRESS				0x40023800UL
#define RCC_CLK_CONFIG_REG_OFFSET		0x08UL
#define RCC_ENABLE_AHB1_OFFSET			0x30UL

#define GPIOA_BASE_ADDR					0x40020000UL
#define GPIOA_MODER_OFFSET  			0x0

#define RCC_CLK_CONFIG_REG_ADDR			(RCC_BASE_ADDRESS + RCC_CLK_CONFIG_REG_OFFSET)
#define RCC_CLK_ENABLE_AHB1_ADDR		(RCC_BASE_ADDRESS + RCC_ENABLE_AHB1_OFFSET)

#define GPIOA_MODER_ADDR				(GPIOA_BASE_ADDR + GPIOA_MODER_OFFSET)

int main(void)
{
	// 1) Configure the RCC_CFGR register
	// pointer for register
	uint32_t *p_RccClkReg = (uint32_t *) RCC_CLK_CONFIG_REG_ADDR;

	// set the bit 22:21 to 00 to configure RCC_CFGR MC01 bit fields to select HSI CLK
	*p_RccClkReg = *p_RccClkReg & 0xFF9FFFFUL;

	// 2) Output to pin PA8 - GPIOA
	// Configure PA8 to AF0 (Alternate function mapping 0) mode t behave as MC01 signal

	// a) since its GPIOA enable the clock peripheral using the RCC clock enable register of AHB1 bus
	uint32_t *pRccEnableAhb1 =  (uint32_t *)RCC_CLK_ENABLE_AHB1_ADDR;

	// set the bits for enable GPIOA (bit0)
	*pRccEnableAhb1 = *pRccEnableAhb1 | 0x00000001;

	//b) & c) come back and do after GPIO section

	//b) Configure the mode of GPIOA pin8 as alternate function mapping mode
	uint32_t *p_GPIOAModerReg = (uint32_t*) GPIOA_MODER_ADDR;
	// which moder?

    /* Loop forever */
	for(;;);
}
